# Generated by Django 3.1.3 on 2020-12-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('product_type', models.CharField(choices=[('Classic', 'Classic'), ('Sport', 'Sport'), ('dm', 'demi-season'), ('Winter', 'Winter')], max_length=40)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Uni', 'Uni')], max_length=20)),
                ('product_model', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('size', models.CharField(choices=[('Child', 'Child'), ('Medium', 'Medium'), ('Large', 'Large'), ('XL', 'XL')], max_length=20)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('manufacturer', models.CharField(max_length=15)),
            ],
        ),
    ]
