# Generated by Django 3.1.3 on 2020-12-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supershop', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not Delivered', 'Not Delivered'), ('In Process', 'In Process'), ('Delivered', 'Delivered')], default='Not Delivered', max_length=20),
        ),
    ]
